// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGm-F3WxJDDwSqMB-XljHMjRPYhBxQ3Lc',
    appId: '1:466063940326:web:6270eb4cbf778ae2a1f927',
    messagingSenderId: '466063940326',
    projectId: 'dbcrudperfumeria0330',
    authDomain: 'dbcrudperfumeria0330.firebaseapp.com',
    storageBucket: 'dbcrudperfumeria0330.firebasestorage.app',
    measurementId: 'G-7XDEJE76RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQenZCVKD4qyOTInICYYcJMMe8i2uFWE',
    appId: '1:466063940326:android:424e71cb10904b7da1f927',
    messagingSenderId: '466063940326',
    projectId: 'dbcrudperfumeria0330',
    storageBucket: 'dbcrudperfumeria0330.firebasestorage.app',
  );
}
